language: python
python:
  - "2.6"
  - "2.7"
before_script:
  - flake8 funfactory
  - mysql -e 'create database _funfactory_test;'
script: FF_DB_USER=travis coverage run tests/run_tests.py
install:
  - pip install -r funfactory/requirements/compiled.txt --use-mirrors
  - pip install -r funfactory/requirements/dev.txt --use-mirrors
  - pip install flake8 coverage --use-mirrors
after_success:
  # Report coverage results to coveralls.io
  - pip install coveralls --use-mirrors
  - coveralls
